Traceback (most recent call last):
  File "./Bias_and_BiasMF_Models.py", line 19, in <module>
    data = pd.read_json('/scratch/as12453/all_data_restaurants_subset.json', lines=True, orient='columns', chunksize=1000000)
  File "/home/as12453/miniconda3/envs/dsga3001/lib/python3.8/site-packages/pandas/util/_decorators.py", line 199, in wrapper
    return func(*args, **kwargs)
  File "/home/as12453/miniconda3/envs/dsga3001/lib/python3.8/site-packages/pandas/util/_decorators.py", line 296, in wrapper
    return func(*args, **kwargs)
  File "/home/as12453/miniconda3/envs/dsga3001/lib/python3.8/site-packages/pandas/io/json/_json.py", line 597, in read_json
    json_reader = JsonReader(
  File "/home/as12453/miniconda3/envs/dsga3001/lib/python3.8/site-packages/pandas/io/json/_json.py", line 679, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/as12453/miniconda3/envs/dsga3001/lib/python3.8/site-packages/pandas/io/json/_json.py", line 718, in _get_data_from_filepath
    data, _ = get_handle(
  File "/home/as12453/miniconda3/envs/dsga3001/lib/python3.8/site-packages/pandas/io/common.py", line 493, in get_handle
    f = open(path_or_buf, mode, encoding=encoding, errors=errors, newline="")
IsADirectoryError: [Errno 21] Is a directory: '/scratch/as12453/all_data_restaurants_subset.json'
